# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20171012_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='name',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='productabstract',
            name='explaintext',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='selectType',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('textarea', 'textarea'), ('picker', 'picker'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('image', 'image'), ('picker-view', 'picker-view'), ('slider', 'slider'), ('switch', 'switch'), ('progress', 'progress'), ('video', 'video'), ('rich-text', 'rich-text')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 14, 43, 2, 537510)),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='prompt',
            field=models.TextField(blank=True, help_text='就是提示这个选择是用来干嘛的，总不能一堆空白让人选呀，text和textarea好歹还有placeholder用来提示', max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set([('product', 'order')]),
        ),
    ]
