# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_auto_20171016_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitems',
            name='ProductAbstract',
        ),
        migrations.AddField(
            model_name='productabstract',
            name='productType',
            field=models.CharField(blank=True, choices=[('商品类型1', '商品类型1'), ('商品类型2', '商品类型2'), ('商品类型3', '商品类型3'), ('商品类型4', '商品类型4')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productabstract',
            name='zone',
            field=models.CharField(blank=True, choices=[('研究生院', '研究生院'), ('教室公寓', '教室公寓')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 17, 58, 58, 528226)),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='zone',
            field=models.CharField(blank=True, choices=[('研究生院', '研究生院'), ('教室公寓', '教室公寓')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='order',
            field=models.CharField(blank=True, help_text='起排序作用的', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='placeholder',
            field=models.CharField(blank=True, help_text='占位符，起提示作用', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='prompt',
            field=models.TextField(blank=True, help_text='会根据selectType自动添加组件name或value', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='selectType',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('textarea', 'textarea'), ('picker', 'picker'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('image', 'image'), ('picker-view', 'picker-view'), ('slider', 'slider'), ('switch', 'switch'), ('progress', 'progress'), ('video', 'video'), ('rich-text', 'rich-text'), ('show-picture', 'show-picture'), ('show-text', 'show-text'), ('show-title', 'show-title')], max_length=100, null=True),
        ),
    ]
