# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_auto_20171029_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='image',
            field=models.ForeignKey(blank=True, help_text='selectType=show-image时填写', null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.ImageItems'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 18, 23, 40, 790500)),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='placeholder',
            field=models.TextField(blank=True, help_text='占位符，起提示作用', max_length=300, null=True),
        ),
    ]
