# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0005_auto_20171029_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='the_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 8, 8, 43, 759207)),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='zone',
            field=models.CharField(blank=True, choices=[('研究生院', '研究生院'), ('教室公寓', '教室公寓'), ('还未选择园区', '还未选择园区')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imageitems',
            name='image_select',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productabstract',
            name='zone',
            field=models.CharField(blank=True, choices=[('研究生院', '研究生院'), ('教室公寓', '教室公寓'), ('还未选择园区', '还未选择园区')], max_length=200, null=True),
        ),
    ]
