# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_auto_20171104_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 21, 36, 53, 26824)),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 21, 36, 53, 18815)),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
