# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0008_auto_20171104_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.ImageField(upload_to='static/up_images')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 18, 35, 57, 621568), null=True)),
            ],
            options={
                'verbose_name': 'order关联的图片',
                'verbose_name_plural': 'order关联的图片',
            },
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 18, 35, 57, 602558)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 18, 35, 57, 615565), null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.Order'),
        ),
    ]
