# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0012_auto_20171109_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.CharField(blank=True, default='', help_text='这是一对多关系，广告方为多', max_length=100, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.ProductAbstract')),
            ],
            options={
                'verbose_name': '广告与商品对应关系',
                'verbose_name_plural': '广告与商品对应关系',
            },
        ),
        migrations.CreateModel(
            name='advertisingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.CharField(blank=True, default='', help_text='广告介绍', max_length=100, null=True)),
                ('banner_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.ImageItems')),
            ],
            options={
                'verbose_name': '广告信息',
                'verbose_name_plural': '广告信息',
            },
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 15, 48, 43, 745531)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 12, 15, 48, 43, 751535), null=True),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 12, 15, 48, 43, 753536), null=True),
        ),
    ]
